-- ArmorData.lua
-- Defines all armor items and their properties

local ArmorData = {
    ["Brown Armor Helmet"] = {
        Name = "Brown Armor Helmet",
        Type = "Helmet",
        Defense = 5,
        Description = "A sturdy brown helmet.",
        itemType = "armor",
        Price = 500,
    },
    ["Brown Armor Suit"] = {
        Name = "Brown Armor Suit",
        Type = "Suit",
        Defense = 15,
        Description = "A tough brown suit for protection.",
        itemType = "armor",
        Price = 1200,
    },
    ["Brown Armor Legs"] = {
        Name = "Brown Armor Legs",
        Type = "Legs",
        Defense = 8,
        Description = "Brown armor for your legs.",
        itemType = "armor",
        Price = 700,
    },
    ["Brown Armor Shoes"] = {
        Name = "Brown Armor Shoes",
        Type = "Shoes",
        Defense = 3,
        Description = "Brown armor shoes for basic protection.",
        itemType = "armor",
        Price = 400,
    },
    ["Iron Armor Helmet"] = {
        Name = "Iron Armor Helmet",
        Type = "Helmet",
        Defense = 20,
        Description = "A sturdy iron helmet.",
        itemType = "armor",
        Price = 2500,
    },
    ["Iron Armor Suit"] = {
        Name = "Iron Armor Suit",
        Type = "Suit",
        Defense = 50,
        Description = "A tough iron suit for protection.",
        itemType = "armor",
        Price = 5000,
    },
    ["Iron Armor Legs"] = {
        Name = "Iron Armor Legs",
        Type = "Legs",
        Defense = 28,
        Description = "Iron armor for your legs.",
        itemType = "armor",
        Price = 3000,
    },
    ["Iron Armor Shoes"] = {
        Name = "Iron Armor Shoes",
        Type = "Shoes",
        Defense = 10,
        Description = "Iron armor shoes for strong protection.",
        itemType = "armor",
        Price = 1200,
    },
    ["Stone Armor Helmet"] = {
        Name = "Stone Armor Helmet",
        Type = "Helmet",
        Defense = 12,
        Description = "A heavy stone helmet.",
        itemType = "armor",
        Price = 1500,
    },
    ["Stone Armor Suit"] = {
        Name = "Stone Armor Suit",
        Type = "Suit",
        Defense = 30,
        Description = "A heavy stone suit for protection.",
        itemType = "armor",
        Price = 3200,
    },
    ["Stone Armor Legs"] = {
        Name = "Stone Armor Legs",
        Type = "Legs",
        Defense = 18,
        Description = "Stone armor for your legs.",
        itemType = "armor",
        Price = 1800,
    },
    ["Stone Armor Shoes"] = {
        Name = "Stone Armor Shoes",
        Type = "Shoes",
        Defense = 6,
        Description = "Stone armor shoes for solid protection.",
        itemType = "armor",
        Price = 800,
    },
    ["Osmium Armor Helmet"] = {
        Name = "Osmium Armor Helmet",
        Type = "Helmet",
        Defense = 35,
        Description = "A rare osmium helmet.",
        itemType = "armor",
        Price = 6000,
    },
    ["Osmium Armor Suit"] = {
        Name = "Osmium Armor Suit",
        Type = "Suit",
        Defense = 90,
        Description = "A rare osmium suit for protection.",
        itemType = "armor",
        Price = 12000,
    },
    ["Osmium Armor Legs"] = {
        Name = "Osmium Armor Legs",
        Type = "Legs",
        Defense = 50,
        Description = "Osmium armor for your legs.",
        itemType = "armor",
        Price = 7000,
    },
    ["Osmium Armor Shoes"] = {
        Name = "Osmium Armor Shoes",
        Type = "Shoes",
        Defense = 18,
        Description = "Osmium armor shoes for rare protection.",
        itemType = "armor",
        Price = 3000,
    },
    ["Red Osmium Armor Helmet"] = {
        Name = "Red Osmium Armor Helmet",
        Type = "Helmet",
        Defense = 50,
        Description = "A legendary red osmium helmet.",
        itemType = "armor",
        Price = 12000,
    },
    ["Red Osmium Armor Suit"] = {
        Name = "Red Osmium Armor Suit",
        Type = "Suit",
        Defense = 120,
        Description = "A legendary red osmium suit for protection.",
        itemType = "armor",
        Price = 25000,
    },
    ["Red Osmium Armor Legs"] = {
        Name = "Red Osmium Armor Legs",
        Type = "Legs",
        Defense = 70,
        Description = "Red osmium armor for your legs.",
        itemType = "armor",
        Price = 14000,
    },
    ["Red Osmium Armor Shoes"] = {
        Name = "Red Osmium Armor Shoes",
        Type = "Shoes",
        Defense = 30,
        Description = "Legendary red osmium armor shoes.",
        itemType = "armor",
        Price = 7000,
    },
}

return ArmorData
